name: desafio-akross
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gerenciamento-de-usuarios
    ports:
      - "5432:5432"
