spring:
  application:
    name: paulo
  datasource:
    url: jdbc:postgresql://localhost:5432/gerenciamento-de-usuarios
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: 'create-drop'

server:
  error:
    include-stacktrace: NEVER
